export type RFW_Languages =
  | 'abap'
  | 'abnf'
  | 'actionscript'
  | 'ada'
  | 'antlr4'
  | 'apacheconf'
  | 'apl'
  | 'applescript'
  | 'aql'
  | 'arduino'
  | 'arff'
  | 'asciidoc'
  | 'asm6502'
  | 'aspnet'
  | 'autohotkey'
  | 'autoit'
  | 'bash'
  | 'basic'
  | 'batch'
  | 'bbcode'
  | 'bison'
  | 'bnf'
  | 'brainfuck'
  | 'brightscript'
  | 'bro'
  | 'c'
  | 'cil'
  | 'clike'
  | 'clojure'
  | 'cmake'
  | 'coffeescript'
  | 'concurnas'
  | 'cpp'
  | 'crystal'
  | 'csharp'
  | 'csp'
  | 'css'
  | 'css-extras'
  | 'd'
  | 'dart'
  | 'dax'
  | 'diff'
  | 'django'
  | 'dns-zone-file'
  | 'docker'
  | 'ebnf'
  | 'eiffel'
  | 'ejs'
  | 'elixir'
  | 'elm'
  | 'erb'
  | 'erlang'
  | 'etlua'
  | 'excel-formula'
  | 'factor'
  | 'firestore-security-rules'
  | 'flow'
  | 'fortran'
  | 'fsharp'
  | 'ftl'
  | 'gcode'
  | 'gdscript'
  | 'gedcom'
  | 'gherkin'
  | 'git'
  | 'glsl'
  | 'gml'
  | 'go'
  | 'graphql'
  | 'groovy'
  | 'haml'
  | 'handlebars'
  | 'haskell'
  | 'haxe'
  | 'hcl'
  | 'hpkp'
  | 'hsts'
  | 'http'
  | 'ichigojam'
  | 'icon'
  | 'inform7'
  | 'ini'
  | 'io'
  | 'j'
  | 'java'
  | 'javadoc'
  | 'javadoclike'
  | 'javascript'
  | 'js'
  | 'javastacktrace'
  | 'jolie'
  | 'jq'
  | 'js-extras'
  | 'js-templates'
  | 'jsdoc'
  | 'json'
  | 'json5'
  | 'jsonp'
  | 'jsx'
  | 'julia'
  | 'keyman'
  | 'kotlin'
  | 'latex'
  | 'latte'
  | 'less'
  | 'lilypond'
  | 'liquid'
  | 'lisp'
  | 'livescript'
  | 'llvm'
  | 'lolcode'
  | 'lua'
  | 'markdown'
  | 'markup'
  | 'matlab'
  | 'mel'
  | 'meta'
  | 'mizar'
  | 'monkey'
  | 'moonscript'
  | 'n1ql'
  | 'n4js'
  | 'nand2tetris-hdl'
  | 'nasm'
  | 'neon'
  | 'nginx'
  | 'nim'
  | 'nix'
  | 'nsis'
  | 'objectivec'
  | 'ocaml'
  | 'opencl'
  | 'oz'
  | 'parigp'
  | 'parser'
  | 'pascal'
  | 'pascaligo'
  | 'pcaxis'
  | 'perl'
  | 'php'
  | 'php-extras'
  | 'phpdoc'
  | 'plsql'
  | 'powerquery'
  | 'powershell'
  | 'processing'
  | 'prolog'
  | 'properties'
  | 'protobuf'
  | 'pug'
  | 'puppet'
  | 'pure'
  | 'python'
  | 'q'
  | 'qml'
  | 'qore'
  | 'r'
  | 'reason'
  | 'regex'
  | 'renpy'
  | 'rest'
  | 'rip'
  | 'roboconf'
  | 'robotframework'
  | 'ruby'
  | 'rust'
  | 'sas'
  | 'sass'
  | 'scala'
  | 'scheme'
  | 'scss'
  | 'shell-session'
  | 'smalltalk'
  | 'smarty'
  | 'solidity'
  | 'solution-file'
  | 'soy'
  | 'sparql'
  | 'splunk-spl'
  | 'sqf'
  | 'sql'
  | 'stylus'
  | 'swift'
  | 't4-cs'
  | 't4-templating'
  | 't4-vb'
  | 'tap'
  | 'tcl'
  | 'textile'
  | 'toml'
  | 'tsx'
  | 'tt2'
  | 'turtle'
  | 'twig'
  | 'typescript'
  | 'vala'
  | 'vbnet'
  | 'velocity'
  | 'verilog'
  | 'vhdl'
  | 'vim'
  | 'visual-basic'
  | 'wasm'
  | 'wiki'
  | 'xeora'
  | 'xojo'
  | 'xquery'
  | 'yaml'
  | 'zig';

export const RFW_codeLangExtensions: { [key: string]: RFW_Languages } = {
  abap: 'abap',
  abnf: 'abnf',
  as: 'actionscript',
  ada: 'ada',
  adb: 'ada',
  ads: 'ada',
  g4: 'antlr4',
  conf: 'nginx',
  apl: 'apl',
  applescript: 'applescript',
  aql: 'aql',
  ino: 'arduino',
  arff: 'arff',
  adoc: 'asciidoc',
  asciidoc: 'asciidoc',
  asm: 'nasm',
  aspx: 'aspnet',
  ascx: 'aspnet',
  ahk: 'autohotkey',
  au3: 'autoit',
  sh: 'bash',
  bash: 'bash',
  bas: 'basic',
  bat: 'batch',
  cmd: 'batch',
  bbcode: 'bbcode',
  y: 'bison',
  bnf: 'bnf',
  b: 'brainfuck',
  bf: 'brainfuck',
  brs: 'brightscript',
  bro: 'bro',
  c: 'clike',
  h: 'objectivec',
  il: 'cil',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  cmake: 'cmake',
  'CMakeLists.txt': 'cmake',
  coffee: 'coffeescript',
  conc: 'concurnas',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  cr: 'crystal',
  cs: 'csharp',
  csp: 'csp',
  css: 'css-extras',
  d: 'd',
  dart: 'dart',
  dax: 'dax',
  diff: 'diff',
  patch: 'diff',
  html: 'markup',
  zone: 'dns-zone-file',
  Dockerfile: 'docker',
  ebnf: 'ebnf',
  e: 'eiffel',
  ejs: 'ejs',
  ex: 'elixir',
  exs: 'elixir',
  elm: 'elm',
  erb: 'erb',
  erl: 'erlang',
  hrl: 'erlang',
  lua: 'lua',
  xlsx: 'excel-formula',
  factor: 'factor',
  rules: 'firestore-security-rules',
  js: 'javascript',
  f: 'fortran',
  f90: 'fortran',
  f95: 'fortran',
  fs: 'fsharp',
  fsi: 'fsharp',
  fsx: 'fsharp',
  ftl: 'ftl',
  gcode: 'gcode',
  gd: 'gdscript',
  ged: 'gedcom',
  feature: 'gherkin',
  gitignore: 'git',
  glsl: 'glsl',
  vert: 'glsl',
  frag: 'glsl',
  gml: 'gml',
  go: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  groovy: 'groovy',
  haml: 'haml',
  hbs: 'handlebars',
  hs: 'haskell',
  hx: 'haxe',
  hcl: 'hcl',
  hpkp: 'hpkp',
  hsts: 'hsts',
  http: 'http',
  ijs: 'j',
  icn: 'icon',
  ni: 'inform7',
  i7x: 'inform7',
  ini: 'ini',
  io: 'io',
  java: 'java',
  stacktrace: 'javastacktrace',
  ol: 'jolie',
  jq: 'jq',
  json: 'json',
  json5: 'json5',
  jsonp: 'jsonp',
  jsx: 'jsx',
  jl: 'julia',
  kmn: 'keyman',
  kt: 'kotlin',
  kts: 'kotlin',
  tex: 'latex',
  latte: 'latte',
  less: 'less',
  ly: 'lilypond',
  liquid: 'liquid',
  lisp: 'lisp',
  ls: 'livescript',
  ll: 'llvm',
  lol: 'lolcode',
  md: 'markdown',
  xml: 'markup',
  m: 'objectivec',
  mel: 'mel',
  meta: 'meta',
  miz: 'mizar',
  monkey: 'monkey',
  moon: 'moonscript',
  n1ql: 'n1ql',
  n4js: 'n4js',
  hdl: 'nand2tetris-hdl',
  neon: 'neon',
  nim: 'nim',
  nix: 'nix',
  nsi: 'nsis',
  ml: 'ocaml',
  mli: 'ocaml',
  cl: 'opencl',
  oz: 'oz',
  gp: 'parigp',
  parser: 'parser',
  pas: 'pascal',
  ligo: 'pascaligo',
  px: 'pcaxis',
  pl: 'perl',
  php: 'php',
  pls: 'plsql',
  pq: 'powerquery',
  ps1: 'powershell',
  pde: 'processing',
  properties: 'properties',
  proto: 'protobuf',
  pug: 'pug',
  pp: 'puppet',
  pure: 'pure',
  py: 'python',
  q: 'qore',
  qml: 'qml',
  r: 'r',
  re: 'reason',
  regex: 'regex',
  rpy: 'renpy',
  rest: 'rest',
  rip: 'rip',
  graph: 'roboconf',
  robot: 'robotframework',
  rb: 'ruby',
  rs: 'rust',
  sas: 'sas',
  sass: 'sass',
  scala: 'scala',
  scm: 'scheme',
  scss: 'scss',
  'sh-session': 'shell-session',
  st: 'smalltalk',
  tpl: 'smarty',
  sol: 'solidity',
  sln: 'solution-file',
  soy: 'soy',
  rq: 'sparql',
  spl: 'splunk-spl',
  sqf: 'sqf',
  sql: 'sql',
  styl: 'stylus',
  swift: 'swift',
  t4: 't4-vb',
  tap: 'tap',
  tcl: 'tcl',
  textile: 'textile',
  toml: 'toml',
  tsx: 'tsx',
  tt2: 'tt2',
  ttl: 'turtle',
  twig: 'twig',
  ts: 'typescript',
  vala: 'vala',
  vb: 'visual-basic',
  vm: 'velocity',
  v: 'verilog',
  vhd: 'vhdl',
  vim: 'vim',
  wasm: 'wasm',
  wiki: 'wiki',
  xeora: 'xeora',
  xojo: 'xojo',
  xq: 'xquery',
  yaml: 'yaml',
  yml: 'yaml',
  zig: 'zig',
};
